kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      listenAddress: "0.0.0.0"
    image: kindest/node:v1.14.10@sha256:81ae5a3237c779efc4dda43cc81c696f88a194abcc4f8fa34f86cf674aa14977
    kubeadmConfigPatches:
    - |
      apiVersion: kubeadm.k8s.io/v1beta2
      kind: JoinConfiguration
      metadata:
        name: config
      nodeRegistration:
        kubeletExtraArgs:
          anonymous-auth: false
          authentication-token-webhook: true
          authorization-mode: Webhook

  - role: worker
    image: kindest/node:v1.14.10@sha256:81ae5a3237c779efc4dda43cc81c696f88a194abcc4f8fa34f86cf674aa14977
    kubeadmConfigPatches:
    - |
      apiVersion: kubeadm.k8s.io/v1beta2
      kind: JoinConfiguration
      metadata:
        name: config
      nodeRegistration:
        kubeletExtraArgs:
          anonymous-auth: false
          authentication-token-webhook: true
          authorization-mode: Webhook
